version: '2.1'

services:
  app:
    volumes:
      - .:/steam-market-analyser
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 10000:10000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    ports:
      - 10001:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
